///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RanorexGitProj
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RanorexGitProjRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("a9db29b7-7f6f-436d-abce-4e21c4aac2b8")]
    public partial class RanorexGitProjRepository : RepoGenBaseFolder
    {
        static RanorexGitProjRepository instance = new RanorexGitProjRepository();

        /// <summary>
        /// Gets the singleton class instance representing the RanorexGitProjRepository element repository.
        /// </summary>
        [RepositoryFolder("a9db29b7-7f6f-436d-abce-4e21c4aac2b8")]
        public static RanorexGitProjRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RanorexGitProjRepository() 
            : base("RanorexGitProjRepository", "/", null, 0, false, "a9db29b7-7f6f-436d-abce-4e21c4aac2b8", ".\\RepositoryImages\\RanorexGitProjRepositorya9db29b7.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a9db29b7-7f6f-436d-abce-4e21c4aac2b8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class RanorexGitProjRepositoryFolders
    {
    }
#pragma warning restore 0436
}